### ISSUE TITLE
Task #6 Method setValueFrameAndPrevFrames() in class Game

### ISSUE THREAD

**Issue by Tomek52** [csGroupProjectcs/Bowling#9]
Made `void setValueFrameAndPrevFrames(int pos, const std::string & value)`. It should call metod checkValue() to set value in frame[pos], and respectly add value in frame[pos-1] and frame[pos-2]

**Comment by anorberciak** [comment]
Could you only change the return value in checkValue(), from int to pair <int, int>. Maybe it will be better, instead of adding a new convertValueToInt() function.
